# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_auth_api: https://github.com/login/oauth/authorize
  github_token_api: https://github.com/login/oauth/access_token
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>

development:
  <<: *default
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["SMTP_USERNAME"] %>
  email_provider_password: <%= ENV["SMTP_PASSWORD"] %>
  touclick_pub_key: <%= ENV["TOUCLICK_PUB_KEY"] %>
  touclick_secret_key: <%= ENV["TOUCLICK_SECRET_KEY"] %>
  qiniu_access_key: <%= ENV["QINIU_ACCESS_KEY"] %>
  qiniu_secret_key: <%= ENV["QINIU_SECRET_KEY"] %>
  qiniu_bucket: <%= ENV["QINIU_BUCKET"] %>
  qiniu_bucket_domain: <%= ENV["QINIU_BUCKET_DOMAIN"] %>
  qiniu_protocol: https
  domain_name: dev.ogx.io
  avatar_host: http://dev.ogx.io
  secret_key_base: 5c2d20f4f56f5ba4012e70a9a2a0ad9b0fabfca15a3ffa4e6dc5b5b9df962f9350a544d35b08fefd55f5f1126b04654ac6ba778c7ae165b3234109322dfbefe9

test:
  domain_name: ogx.io
  avatar_host: http://dev.ogx.io
  secret_key_base: 24359438f877f0167066777d9e57cadfd5f2473430039d1655dd02e40cab6d163f347f65c2cadf41bd1806845f9e4f48fd5335b244324782e85ed548859decd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["SMTP_USERNAME"] %>
  email_provider_password: <%= ENV["SMTP_PASSWORD"] %>
  touclick_pub_key: <%= ENV["TOUCLICK_PUB_KEY"] %>
  touclick_secret_key: <%= ENV["TOUCLICK_SECRET_KEY"] %>
  qiniu_access_key: <%= ENV["QINIU_ACCESS_KEY"] %>
  qiniu_secret_key: <%= ENV["QINIU_SECRET_KEY"] %>
  qiniu_bucket: <%= ENV["QINIU_BUCKET"] %>
  qiniu_bucket_domain: <%= ENV["QINIU_BUCKET_DOMAIN"] %>
  qiniu_protocol: https
  domain_name: ogx.io
  avatar_host: https://ogx.io
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
